/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InternalFrame;

import Vista.VistaPrincipal;
import java.awt.Container;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author ramos
 */
public class InternalBajaAlumno extends javax.swing.JInternalFrame {

    private VistaPrincipal vistaprincipal;
    
    public InternalBajaAlumno(VistaPrincipal vistaprincipal) {
        this.vistaprincipal = vistaprincipal;
        BasicInternalFrameUI ui = (BasicInternalFrameUI) getUI();
        Container northPane = ui.getNorthPane();
        northPane.removeMouseMotionListener(ui.getNorthPane().getMouseMotionListeners()[0]);
        remove(northPane);
        setBorder(null);  
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnCerrarPestañaBajaAlumno = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        MATRICULA = new javax.swing.JLabel();
        txtObservaciónBaja = new javax.swing.JTextField();
        OBSERVACIÓN = new javax.swing.JLabel();
        NOMBRE = new javax.swing.JLabel();
        PATERNO = new javax.swing.JLabel();
        MATERNO = new javax.swing.JLabel();
        txtNombreBaja = new javax.swing.JTextField();
        txtPaternoBaja = new javax.swing.JTextField();
        txtMaternoBaja = new javax.swing.JTextField();
        SEMESTRE = new javax.swing.JLabel();
        txtSemestreBaja = new javax.swing.JTextField();
        btnGenerarBaja = new javax.swing.JButton();
        cbxMatriculaBaja = new javax.swing.JComboBox<>();
        panelAcciones = new javax.swing.JPanel();
        btnModificarBaja = new javax.swing.JButton();
        btnCancelarBaja = new javax.swing.JButton();
        btnEliminarBaja = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableBajas = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        lblBusquedaNombre = new javax.swing.JLabel();
        cbxBusquedaNombre = new javax.swing.JComboBox<>();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("APARTADO DE BAJAS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(507, 0, -1, -1));

        btnCerrarPestañaBajaAlumno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/20xCerrarPestaña.png"))); // NOI18N
        btnCerrarPestañaBajaAlumno.setText("Cerrar Pestaña");
        btnCerrarPestañaBajaAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarPestañaBajaAlumnoActionPerformed(evt);
            }
        });
        getContentPane().add(btnCerrarPestañaBajaAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 400, 161, -1));

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        MATRICULA.setText("MATRICULA: ");

        OBSERVACIÓN.setText("OBSERVACIÓN:");

        NOMBRE.setText("NOMBRE: ");

        PATERNO.setText("APELLIDO PATERNO: ");

        MATERNO.setText("APELLIDO MATERNO:");

        SEMESTRE.setText("SEMESTRE: ");

        btnGenerarBaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/x20Pdf.png"))); // NOI18N
        btnGenerarBaja.setText("GENERAR BAJA");

        cbxMatriculaBaja.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(OBSERVACIÓN)
                        .addGap(54, 54, 54)
                        .addComponent(txtObservaciónBaja))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MATERNO)
                            .addComponent(PATERNO)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(MATRICULA)
                                    .addComponent(NOMBRE)
                                    .addComponent(SEMESTRE))
                                .addGap(65, 65, 65)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtSemestreBaja)
                                    .addComponent(cbxMatriculaBaja, 0, 202, Short.MAX_VALUE)
                                    .addComponent(txtNombreBaja)
                                    .addComponent(txtPaternoBaja, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtMaternoBaja, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 105, Short.MAX_VALUE)
                .addComponent(btnGenerarBaja, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MATRICULA)
                    .addComponent(cbxMatriculaBaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NOMBRE)
                    .addComponent(txtNombreBaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PATERNO)
                    .addComponent(txtPaternoBaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MATERNO)
                    .addComponent(txtMaternoBaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SEMESTRE)
                    .addComponent(txtSemestreBaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtObservaciónBaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OBSERVACIÓN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(btnGenerarBaja)
                .addGap(24, 24, 24))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 26, -1, -1));

        panelAcciones.setBackground(new java.awt.Color(204, 255, 204));

        btnModificarBaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/20xModificar.png"))); // NOI18N
        btnModificarBaja.setText("Modificar");

        btnCancelarBaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/20xCancelar.png"))); // NOI18N
        btnCancelarBaja.setText("Cancelar");

        btnEliminarBaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/20xEliminar.png"))); // NOI18N
        btnEliminarBaja.setText("Eliminar");

        javax.swing.GroupLayout panelAccionesLayout = new javax.swing.GroupLayout(panelAcciones);
        panelAcciones.setLayout(panelAccionesLayout);
        panelAccionesLayout.setHorizontalGroup(
            panelAccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAccionesLayout.createSequentialGroup()
                .addGroup(panelAccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAccionesLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(btnCancelarBaja)
                        .addGap(56, 56, 56)
                        .addComponent(btnEliminarBaja))
                    .addGroup(panelAccionesLayout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(btnModificarBaja)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        panelAccionesLayout.setVerticalGroup(
            panelAccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAccionesLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(btnModificarBaja)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelAccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelarBaja)
                    .addComponent(btnEliminarBaja))
                .addContainerGap())
        );

        getContentPane().add(panelAcciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, 100));

        tableBajas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MATRICULA", "NOMBRE", "APE. PATERNO", "APE. MATERNO", "cod.Licenciatura", "LICENCIATURA", "SEMESTRE"
            }
        ));
        jScrollPane1.setViewportView(tableBajas);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, 650, 223));

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));

        lblBusquedaNombre.setText("BUSQUEDA POR NOMBRE:");

        cbxBusquedaNombre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBusquedaNombre)
                .addGap(18, 18, 18)
                .addComponent(cbxBusquedaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(274, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBusquedaNombre)
                    .addComponent(cbxBusquedaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, 650, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarPestañaBajaAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarPestañaBajaAlumnoActionPerformed
        vistaprincipal.cerrarBajaAlumno();
    }//GEN-LAST:event_btnCerrarPestañaBajaAlumnoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MATERNO;
    private javax.swing.JLabel MATRICULA;
    private javax.swing.JLabel NOMBRE;
    private javax.swing.JLabel OBSERVACIÓN;
    private javax.swing.JLabel PATERNO;
    private javax.swing.JLabel SEMESTRE;
    private javax.swing.JButton btnCancelarBaja;
    private javax.swing.JButton btnCerrarPestañaBajaAlumno;
    private javax.swing.JButton btnEliminarBaja;
    private javax.swing.JButton btnGenerarBaja;
    private javax.swing.JButton btnModificarBaja;
    private javax.swing.JComboBox<String> cbxBusquedaNombre;
    private javax.swing.JComboBox<String> cbxMatriculaBaja;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBusquedaNombre;
    private javax.swing.JPanel panelAcciones;
    private javax.swing.JTable tableBajas;
    private javax.swing.JTextField txtMaternoBaja;
    private javax.swing.JTextField txtNombreBaja;
    private javax.swing.JTextField txtObservaciónBaja;
    private javax.swing.JTextField txtPaternoBaja;
    private javax.swing.JTextField txtSemestreBaja;
    // End of variables declaration//GEN-END:variables
}
